config/routes.rb
Rails.application.routes.draw do

  get 'tweet_students/index'
  get 'tweet_teachers/index'

  devise_for :teachers, controllers: {
    sessions: 'teachers/sessions',
    passwords: 'teachers/passwords',
    registrations: 'teachers/registrations'
  }
  

  devise_for :students, controllers: {
    sessions: 'students/sessions',
    passwords: 'students/passwords',
    registrations: 'students/registrations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tweet_students do
    resources :likes, only: [:create, :destroy]
  end

  resources :tweet_teachers

  resources :students do
    resources :relations, only: [:create, :destroy]
  end

  resources :teachers
  resources :finals
  resources :middles
  resources :subjects
  resources :todos
  resources :schedules

  resources :conversations do
    resources :messages
  end
  
  patch 'tweet_students/:id/all_destroy' => 'tweet_students#all_destroy', as:'all_destroy_tweet_students'
  get 'students/:id/callender' => 'students#callender' , as: 'student_callender'
  get 'hello/index' => 'hello#index'
  root 'hello#index'
  get 'hello/link' => 'hello#link'
  
  get 'tweet_students/:id/history' => 'tweet_students#history_index', as:'history_index_tweet_students'
  get 'tweet_students/:id/history/:id' => 'tweet_students#history_show', as:'history_show_tweet_student'
  patch 'tweet_students/:id/history/:id' => 'tweet_students#physical_destroy', as:'physical_destroy_tweet_students'

  patch 'tweet_teachers/:id/all_destroy' => 'tweet_teachers#all_destroy', as:'all_destroy_tweet_teachers'
  get 'tweet_teachers/:id/history' => 'tweet_teachers#history_index', as:'history_index_tweet_teachers'
  get 'tweet_teachers/:id/history/:id' => 'tweet_teachers#history_show', as:'history_show_tweet_teacher'
  patch 'tweet_teachers/:id/history/:id' => 'tweet_teachers#physical_destroy', as:'physical_destroy_tweet_teachers'




end

app/models/tweet_student.rb
class TweetStudent < ApplicationRecord

    belongs_to :student
    belongs_to :middle

    has_many :likes, dependent: :destroy
    has_many :liked_teachers, through: :likes, source: :teacher

    mount_uploader :image, ImageUploader
    
    acts_as_paranoid
end

app/controllers/tweet_students_controller.rb
class TweetStudentsController < ApplicationController
    before_action :authenticate_student!
    def index
        @student = Student.find(current_student.id)
        @tweet_students = @student.tweet_students.without_deleted
        @final = Final.where( student_id: Student.find(current_student.id) ).last
        @middle = Middle.where( student_id: Student.find(current_student.id)).last
        @subjects = Subject.where( student_id: Student.find(current_student.id))
        @todos = Todo.where( student_id: Student.find(current_student.id) )

        @teacher = Teacher.find_by(id: @student.teacher_id)

        @tweet_student_new = TweetStudent.new


        

    end
    
    def new
        @tweet_students = TweetStudent.new
        @tweet_students.num = params[:num]
        @middle = Middle.where( student_id: Student.find(current_student.id)).last
    end

    def create
        TweetStudent.create(tweet_student_params)
        @tweet_students = Student.find(current_student.id).tweet_students.without_deleted

        @student = Student.find(current_student.id)
        @tweet_students = @student.tweet_students.without_deleted
        @final = Final.where( student_id: Student.find(current_student.id) ).last
        @middle = Middle.where( student_id: Student.find(current_student.id)).last
        @subjects = Subject.where( student_id: Student.find(current_student.id))
        @todos = Todo.where( student_id: Student.find(current_student.id) )
        @teacher = Teacher.find_by(id: @student.teacher_id)
    end

    def edit
        @tweet_student = TweetStudent.find(params[:id])
    end

    def update
        tweet_student = TweetStudent.find(params[:id])
        if tweet_student.update(tweet_student_params)
            redirect_to :action => "index"
        else
            redirect_to :action =>  "edit"
        end
    end

    def destroy
        tweet_student = TweetStudent.find(params[:id])
        tweet_student.destroy
        redirect_to action: :index
    end

    def all_destroy
        tweet_students = TweetStudent.where(student_id: params[:student_id]).without_deleted
        tweet_students.each do |t|
            t.destroy
        end
        redirect_to action: :index
    end

    def history_index
        @middles = Middle.where( student_id: Student.find(current_student.id)).all
    end

    def history_show
        @student = Student.find(current_student.id)
        # student_id = @student.id
        @tweet_students = @student.tweet_students.where(middle_id: params[:id]).with_deleted
        # relation = Relation.find_by( student_id: Student.find(current_student.id) )
        @final = Final.where( student_id: Student.find(current_student.id) ).last
        @middles = Middle.where( student_id: Student.find(current_student.id)).all
        @subjects = Subject.where( student_id: Student.find(current_student.id))
        # @todos = Todo.where( student_id: Student.find(current_student.id) )
        @teacher = Teacher.find_by(id: @student.teacher_id)
        @middle = Middle.find(params[:id])
    end

    def physical_destroy
        tweet_students = TweetStudent.where(middle_id: params[:middle_id]).with_deleted
        tweet_students.each do |t|
            t.really_destroy!
        end
        middle = Middle.find(params[:middle_id])
        middle.destroy
        redirect_to action: :history_index
    end

    private
    def tweet_student_params
        params.require(:tweet_student).permit(:body, :student_id, :num, :achivement, :image, :notget, :middle_id)
    end

end

app/views/tweet_students/create.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide');
location.reload();

app/views/tweet_students/edit.html.erb
<%= form_for @tweet_student do |f| %>
    <div class = "field" >
        <%= f.label :進捗どうだった？ %>
        <%= f.text_field :body, :size =>140 %>
    </div>

    <div class="field">
        <%= f.label :わからなかったところは？ %>
        <%= f.text_field :notget, :size =>140 %>
    </div>

    <div class="field">
        <%= f.label :画像添付 %>
        <%= f.file_field :image %>
    </div>

    <div class="field">
        <%= f.label :達成度 %>
        <%= f.select :achivement, ['0','10','20','30','40','50','60','70','80','90','100'], {include_blank: '選択する'} %>
    </div>

    <%= f.hidden_field :num, :value => @tweet_student.num %>
    <%= f.hidden_field :middle_id, :value => @tweet_student.middle_id %>
    <%= f.submit "編集する" %>
<% end %>

app/views/tweet_students/history_index.html.erb
<% @middles.each do |m| %>
    <%= link_to m.body, history_show_tweet_student_path(m.id) %>
<% end %>

app/views/tweet_students/history_show.html.erb
<% @middles.each do |m| %>
    <%= link_to m.body, history_show_tweet_student_path(m.id) %>
<% end %>

<%= link_to "履歴削除", physical_destroy_tweet_students_path( :middle_id => @middle.id ), method: :patch %>

<div class="container">
    <div class="row">
        <% i=1 %>
        <% while i < 6 %>
            <div class="col-xs-6 col-sm-4">
                <div class="box">
                    <div class="subject">
                        <% s = @subjects.where(num:i).last %>
                        <% if s.present? %>
                            <%= s.body %>
                        <% end %>
                    </div>
                    <div class="tweets">
                        <% tweet_students = @tweet_students.with_deleted.where(num:i).order(id: :DESC) %>
                        <% tweet_students.each do |t| %>
                            <div class = "tweet">
                                <div class="field">
                                    <%= t.body %>
                                </div>
                                <div class="field">
                                    <%= t.notget %>
                                </div>
                                <div class="field">
                                    <%=  image_tag t.image_url, class: 'image' if t.image? %>
                                </div>
                                <div class="field">
                                    <%= t.achivement %>
                                </div>
                                <div class="field">
                                    <%= l t.created_at, format: :short %>
                                </div>
                                <div class="field">
                                    <i class="fas fa-heart"></i><%= t.likes.count %>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
                <% i=i+1 %>
            </div>
        <% end %>
    </div>
</div>

app/views/tweet_students/index.html.erb
<%= stylesheet_link_tag "index", :media => "all" %>
<h2><%= @student.name %>の進捗</h2>

<div class="goal">
    <p>最終目標</p>
    <div class="final-container">
        <div class="final">
            <% if @final.present? %>
                <%= @final.body %>
            <% end %>
        </div>
    </div>
    <p>中間目標</p>
    <div class="middle-container">
        <div class="middle">
            <% if @middle.present? %>
                <%= @middle.body %>
            <% end %>
        </div>
    </div>
</div>

<%= button_to "全部削除", all_destroy_tweet_students_path(current_student.id, :student_id => current_student.id), method: :patch %>
<%= link_to "履歴", history_index_tweet_students_path(current_student.id) %>
<div class="container">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        進捗報告
    </button>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">進捗</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <%= form_for  @tweet_student_new , remote: true do |f| %>
                    <div class="modal-body">
                        <div class="form-group">
                            <%= f.label :教科 %>
                            <%= f.select :num, @subjects.all.map { |subject| [subject.body, subject.num] },{include_blank: '選択ボックス'}%>
                        </div>
                        <div class = "form-group" >
                            <%= f.label :進捗どうだった？ %>
                            <%= f.text_field :body, class: "form-controll" %>
                        </div>
                        <div class="form-group">
                            <%= f.label :わからなかったところは？ %>
                            <%= f.text_field :notget, class: "form-controll" %>
                        </div>
                        <div class="form-group">
                            <%= f.label :画像添付 %>
                            <%= f.file_field :image %>
                        </div>
                        <div class="form-group">
                            <%= f.label :達成度 %>
                            <%= f.select :achivement, ['0','10','20','30','40','50','60','70','80','90','100'], {include_blank: '選択する'} %>
                        </div>
                        <%= f.hidden_field :student_id, :value => current_student.id %>
                        <% if @middle.present? %>
                            <%= f.hidden_field :middle_id, :value => @middle.id %>
                        <% end %>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <%= f.submit "報告する", class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
    <% i=1 %>
    <% while i < 6 %>
    <div class="col-xs-6 col-sm-4">
        <div class="box">
            <div class="subject bg-light text-dark">
                <% s = @subjects.where(num:i).last %>
                <% if s.present? %>
                    <%= s.body %>
                <% end %>
            </div>
            <div class="todo">
                <% t = @todos.where(num:i).last %>
                <% if t.present? %>
                    <%= t.body %>
                <% end %>
            </div>
            <div class="overflow-auto" style="width:100%; height:400px;">
                <div class="tweets">
                    <% tweet_students_data = @tweet_students.where(num:i).order(id: :DESC) %>
                    <% tweet_students_data.each do |t| %>
                        <div class="card">
                        <div class = "tweet">
                            <div class="field">
                                <%= t.body %>
                            </div>
                            <div class="field notget">
                                <%= t.notget %>
                            </div>
                            <div class="field">
                                <%=  image_tag t.image_url, class: 'image' if t.image? %>
                            </div>
                            <div class="field">
                                <%= t.achivement %>
                            </div>
                            <div class="field">
                                <%= l t.created_at, format: :short %>
                            </div>
                            <div class="field">
                                <i class="fas fa-heart"></i><%= t.likes.count %>
                            </div>
                            <div class="field">
                                <%= link_to edit_tweet_student_path(t.id), method: :get do %>
                                    <i class="fa-solid fa-pen-to-square"></i>
                                <% end %>
                                <%= link_to tweet_student_path(t.id), method: :delete do %>
                                    <i class="fa-solid fa-trash-can"></i>
                                <% end %>
                            </div>
                        </div>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="graph">
                <% subject = @subjects.where(num:i) %>
                <% subject.each do |s| %>
                    <%= line_chart [ {name: s.body, data: @tweet_students.where(num:i).map{|t| t.slice(:created_at, :achivement).values} }] %>
                <% end %>
            </div>
        </div>
        <% i=i+1 %>
        </div>
    <% end %>
    </div>
</div>

app/views/tweet_students/new.html.erb
<h1> Tutor </h1>
<h3> 進捗投稿画面 </h3>
<%= form_with model: @tweet_students do |f| %>
    <div class = "field" >
        <%= f.label :進捗どうだった？ %>
        <%= f.text_field :body, :size =>140 %>
    </div>

    <div class="field">
        <%= f.label :わからなかったところは？ %>
        <%= f.text_field :notget, :size =>140 %>
    </div>

    <div class="field">
        <%= f.label :画像添付 %>
        <%= f.file_field :image %>
    </div>

    <div class="field">
        <%= f.label :達成度 %>
        <%= f.select :achivement, ['0','10','20','30','40','50','60','70','80','90','100'], {include_blank: '選択する'} %>
    </div>

    <%= f.hidden_field :num, :value => @tweet_students.num %>
    <%= f.hidden_field :middle_id, :value => @middle.id %>

    <%= f.submit "投稿する" %>
<% end %>