config/routes.rb
Rails.application.routes.draw do

  get 'tweet_students/index'
  get 'tweet_teachers/index'

  devise_for :teachers, controllers: {
    sessions: 'teachers/sessions',
    passwords: 'teachers/passwords',
    registrations: 'teachers/registrations'
  }
  

  devise_for :students, controllers: {
    sessions: 'students/sessions',
    passwords: 'students/passwords',
    registrations: 'students/registrations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tweet_students do
    resources :likes, only: [:create, :destroy]
  end

  resources :tweet_teachers

  resources :students do
    resources :relations, only: [:create, :destroy]
  end

  resources :teachers
  resources :finals
  resources :middles
  resources :subjects
  resources :todos
  resources :schedules

  resources :conversations do
    resources :messages
  end
  
  patch 'tweet_students/:id/all_destroy' => 'tweet_students#all_destroy', as:'all_destroy_tweet_students'
  get 'students/:id/callender' => 'students#callender' , as: 'student_callender'
  get 'hello/index' => 'hello#index'
  root 'hello#index'
  get 'hello/link' => 'hello#link'
  
  get 'tweet_students/:id/history' => 'tweet_students#history_index', as:'history_index_tweet_students'
  get 'tweet_students/:id/history/:id' => 'tweet_students#history_show', as:'history_show_tweet_student'
  patch 'tweet_students/:id/history/:id' => 'tweet_students#physical_destroy', as:'physical_destroy_tweet_students'

  patch 'tweet_teachers/:id/all_destroy' => 'tweet_teachers#all_destroy', as:'all_destroy_tweet_teachers'
  get 'tweet_teachers/:id/history' => 'tweet_teachers#history_index', as:'history_index_tweet_teachers'
  get 'tweet_teachers/:id/history/:id' => 'tweet_teachers#history_show', as:'history_show_tweet_teacher'
  patch 'tweet_teachers/:id/history/:id' => 'tweet_teachers#physical_destroy', as:'physical_destroy_tweet_teachers'




end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :teacher
    belongs_to :student
    belongs_to :tweet_student
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  has_many :messages, dependent: :destroy
end

app/models/final.rb
class Final < ApplicationRecord
    belongs_to :teacher
    belongs_to :student
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet_student
  belongs_to :teacher

#  validates_uniqueness_of :tweet_student_id, scope: :teacher_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  belongs_to :conversation
end

app/models/middle.rb
class Middle < ApplicationRecord
    belongs_to :teacher
    belongs_to :student
    has_many :tweet_students
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  validates_uniqueness_of :student_id, scope: :teacher_id
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :teacher
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweet_students, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relations, dependent: :destroy
  has_many :relationed_teachers, through: :relations, source: :teacher
  has_many :subjects, dependent: :destroy
  has_many :finals, dependent: :destroy
  has_many :middles, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :conversations, dependent: :destroy
  has_many :messages
  has_many :schedules
  
  belongs_to :teacher

  validates :name, presence: true
  validates :profile, length: { maximum:200 }

  mount_uploader :image, ImageUploader

  def already_liked?(tweet_student)
    self.likes.exists?(tweet_student_id: tweet_student.id)
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :liked_tweet_students, through: :likes, source: :tweet_student
  has_many :comments, dependent: :destroy
  has_many :subjects, dependent: :destroy
  has_many :finals, dependent: :destroy
  has_many :middles, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :relations, dependent: :destroy
  has_many :relationed_students, through: :relations, source: :student
  has_many :conversations, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :students
  has_many :schedules

  validates :name, presence: true
  validates :profile, length: { maximum:200 }

  mount_uploader :image, ImageUploader

  def already_liked?(tweet_student)
    self.likes.exists?(tweet_student_id: tweet_student.id)
  end

  def already_relationed?(student)
    self.relations.exists?(student_id: student.id)
  end

end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :teacher
    belongs_to :student
end

app/models/tweet_student.rb
class TweetStudent < ApplicationRecord

    belongs_to :student
    belongs_to :middle

    has_many :likes, dependent: :destroy
    has_many :liked_teachers, through: :likes, source: :teacher

    mount_uploader :image, ImageUploader
    
    acts_as_paranoid
end

app/models/tweet_teacher.rb
class TweetTeacher < ApplicationRecord
    
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

    def show
        @conversation = Conversation.find(params[:id])
        @message = Message.new
        @messages = @conversation.messages
        if teacher_signed_in?
            if @conversation.teacher.id == current_teacher.id
                @student = @conversation.student
            else
                redirect_to "/"
            end
        elsif student_signed_in?
            if @conversation.student.id == current_student.id
                @teacher = @conversation.teacher
            else
                redirect_to '/'
            end
        end
    end


    def create
        if teacher_signed_in?
            @conversation = Conversation.new(conversation_student_params)
            @conversation.teacher_id = current_teacher.id
        elsif student_signed_in?
            @conversation = Conversation.new
            @conversation.teacher_id = params[:teacher_id]
            @conversation.student_id = current_student.id
        end

        if @conversation.save
            redirect_to :action => "show", :id => @conversation.id
        else
            redirect_to "/"
        end
    end

    private
    def conversation_student_params
        params.require(:conversation).permit(:student_id)
    end

    def conversation_teacher_params
        params.require(:conversation).permit(:teacher_id)
    end



end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/finals_helper.rb
module FinalsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mediums_helper.rb
module MediumsHelper
end

app/helpers/middles_helper.rb
module MiddlesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/conversations/show.html.erb
<%= stylesheet_link_tag 'conversations', :media => "all" %>

<div class="chat-header"></div>
<div class="chat-container">
    <% if teacher_signed_in? %>
        <h3 class="room-name"><%= @student.name %>とのチャットルーム</h3>
        <div class="chat-field">
            <% @messages.each do |m| %>
                <% if m.is_teacher %>
                    <div class="right-message">
                        <div class="sb-box">
                            <div class="icon-img icon-img-right">
                                <%= image_tag current_teacher.image_url if current_teacher.image? %>
                            </div>
                            <div class="icon-name icon-name-right">
                                <%= current_teacher.name %>
                            </div>
                            <div class="sb-side sb-side-right">
                                <div class="sb-txt sb-txt-right">
                                    <%= m.body %>
                                </div>
                            </div>
                        </div>
                    </div>
                <% else %>
                    <div class="left-message">
                        <div class="sb-box">
                            <div class="icon-img icon-img-left">
                                <%= image_tag @student.image_url if @student.image? %>
                            </div>
                            <div class="icon-name icon-name-left">
                                <%= @student.name %>
                            </div>
                            <div class="sb-side sb-side-left">
                                <div class="sb-txt sb-txt-left">
                                    <%= m.body %>
                                </div>
                            </div>                            
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    <% elsif student_signed_in?%>
        <h3 class="room-name"><%= @teacher.name %>先生とのチャットルーム</h3>
        <div class="chat-field">
            <% @messages.each do |m| %>
                <% if m.is_teacher %>
                    <div class="left-message">
                        <div class="sb-box">
                            <div class="icon-img icon-img-left">
                                <%= image_tag @teacher.image_url if @teacher.image? %>
                            </div>
                            <div class="icon-name icon-name-left">
                                <%= @teacher.name %>
                            </div>
                            <div class="sb-side sb-side-left">
                                <div class="sb-txt sb-txt-left">
                                    <%= m.body %>
                                </div>
                            </div>
                        </div>
                    </div>
                <% else %>
                    <div class="right-message">
                        <div class="sb-box">
                            <div class="icon-img icon-img-right">
                                <%= image_tag current_student.image_url if current_student.image? %>
                            </div>
                            <div class="icon-name icon-name-right">
                                <%= current_student.name %>
                            </div>
                            <div class="sb-side sb-side-right">
                                <div class="sb-txt sb-txt-right">
                                    <%= m.body %>
                                </div>
                            </div>                            
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    <% end %>
    <div class="send">
        <%= form_with url: conversation_messages_path(@conversation) do |f| %>
            <%= f.hidden_field :conversation_id, :value => @conversation.id %>
            <%= f.text_area :body , class:'send-message'%> 
            <%= f.button :type => "submit", class:'send-btn' do %>
                <i class="fa-regular fa-paper-plane fa-2xl"></i>
            <% end %>
        <% end %>
    </div>
</div>
<div class="chat-fotter"></div>