config/routes.rb
Rails.application.routes.draw do

  get 'tweet_students/index'
  get 'tweet_teachers/index'

  devise_for :teachers, controllers: {
    sessions: 'teachers/sessions',
    passwords: 'teachers/passwords',
    registrations: 'teachers/registrations'
  }
  

  devise_for :students, controllers: {
    sessions: 'students/sessions',
    passwords: 'students/passwords',
    registrations: 'students/registrations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tweet_students do
    resources :likes, only: [:create, :destroy]
  end

  resources :tweet_teachers

  resources :students do
    resources :relations, only: [:create, :destroy]
  end

  resources :teachers
  resources :finals
  resources :middles
  resources :subjects
  resources :todos
  resources :schedules

  resources :conversations do
    resources :messages
  end
  
  patch 'tweet_students/:id/all_destroy' => 'tweet_students#all_destroy', as:'all_destroy_tweet_students'
  get 'students/:id/callender' => 'students#callender' , as: 'student_callender'
  get 'hello/index' => 'hello#index'
  root 'hello#index'
  get 'hello/link' => 'hello#link'
  
  get 'tweet_students/:id/history' => 'tweet_students#history_index', as:'history_index_tweet_students'
  get 'tweet_students/:id/history/:id' => 'tweet_students#history_show', as:'history_show_tweet_student'
  patch 'tweet_students/:id/history/:id' => 'tweet_students#physical_destroy', as:'physical_destroy_tweet_students'

  patch 'tweet_teachers/:id/all_destroy' => 'tweet_teachers#all_destroy', as:'all_destroy_tweet_teachers'
  get 'tweet_teachers/:id/history' => 'tweet_teachers#history_index', as:'history_index_tweet_teachers'
  get 'tweet_teachers/:id/history/:id' => 'tweet_teachers#history_show', as:'history_show_tweet_teacher'
  patch 'tweet_teachers/:id/history/:id' => 'tweet_teachers#physical_destroy', as:'physical_destroy_tweet_teachers'




end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :teacher
    belongs_to :student
    belongs_to :tweet_student
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  has_many :messages, dependent: :destroy
end

app/models/final.rb
class Final < ApplicationRecord
    belongs_to :teacher
    belongs_to :student
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet_student
  belongs_to :teacher

#  validates_uniqueness_of :tweet_student_id, scope: :teacher_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  belongs_to :conversation
end

app/models/middle.rb
class Middle < ApplicationRecord
    belongs_to :teacher
    belongs_to :student
    has_many :tweet_students
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  validates_uniqueness_of :student_id, scope: :teacher_id
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :teacher
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweet_students, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relations, dependent: :destroy
  has_many :relationed_teachers, through: :relations, source: :teacher
  has_many :subjects, dependent: :destroy
  has_many :finals, dependent: :destroy
  has_many :middles, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :conversations, dependent: :destroy
  has_many :messages
  has_many :schedules
  
  belongs_to :teacher

  validates :name, presence: true
  validates :profile, length: { maximum:200 }

  mount_uploader :image, ImageUploader

  def already_liked?(tweet_student)
    self.likes.exists?(tweet_student_id: tweet_student.id)
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :liked_tweet_students, through: :likes, source: :tweet_student
  has_many :comments, dependent: :destroy
  has_many :subjects, dependent: :destroy
  has_many :finals, dependent: :destroy
  has_many :middles, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :relations, dependent: :destroy
  has_many :relationed_students, through: :relations, source: :student
  has_many :conversations, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :students
  has_many :schedules

  validates :name, presence: true
  validates :profile, length: { maximum:200 }

  mount_uploader :image, ImageUploader

  def already_liked?(tweet_student)
    self.likes.exists?(tweet_student_id: tweet_student.id)
  end

  def already_relationed?(student)
    self.relations.exists?(student_id: student.id)
  end

end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :teacher
    belongs_to :student
end

app/models/tweet_student.rb
class TweetStudent < ApplicationRecord

    belongs_to :student
    belongs_to :middle

    has_many :likes, dependent: :destroy
    has_many :liked_teachers, through: :likes, source: :teacher

    mount_uploader :image, ImageUploader
    
    acts_as_paranoid
end

app/models/tweet_teacher.rb
class TweetTeacher < ApplicationRecord
    
end

app/controllers/tweet_teachers_controller.rb
class TweetTeachersController < ApplicationController
    before_action :authenticate_teacher!
    def show
        # id = params[:id].select(id)
        @final = Final.where( student_id: params[:id]).last
        @middle = Middle.where( student_id: params[:id] ).last
        @subjects = Subject.where( student_id: params[:id] )
        @todos = Todo.where( student_id: params[:id] )
        @student = Student.find( params[:id])
        @tweet_students = TweetStudent.where( student_id: params[:id] )
        @teacher = Teacher.find(current_teacher.id)
        
    end

    def index
        @teacher = Teacher.find(current_teacher.id)
        @students = Student.where( teacher_id: current_teacher.id)
        @schedules = Schedule.where( teacher_id: current_teacher.id).all
    end
    
    def all_destroy
        tweet_students = TweetStudent.where(student_id: params[:id]).without_deleted
        tweet_students.each do |t|
            t.destroy
        end
        redirect_to tweet_teacher_path(params[:id])
    end

    def history_index
        @middles = Middle.where( student_id: params[:id]).all
        @student = Student.find(params[:id])
    end

    def history_show
        @final = Final.where( student_id: params[:student_id]).last
        @middles = Middle.where( student_id: params[:student_id] ).all
        @subjects = Subject.where( student_id: params[:student_id] )
        @student = Student.find( params[:student_id])
        @tweet_students = TweetStudent.where( student_id: params[:student_id] ).with_deleted
        @middle = Middle.find(params[:id])
    end

    def physical_destroy
        tweet_students = TweetStudent.where(middle_id: params[:middle_id]).with_deleted
        tweet_students.each do |t|
            t.really_destroy!
        end
        middle = Middle.find(params[:middle_id])
        middle.destroy
        redirect_to history_index_tweet_teachers_path(params[:student_id])
    end

    
end

app/helpers/finals_helper.rb
module FinalsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mediums_helper.rb
module MediumsHelper
end

app/helpers/middles_helper.rb
module MiddlesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/tweet_teachers_helper.rb
module TweetTeachersHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweet_teachers/history_index.html.erb
<% @middles.each do |m| %>
    <%= link_to m.body, history_show_tweet_teacher_path(m.id, :student_id => @student.id) %>
<% end %>

app/views/tweet_teachers/history_show.html.erb
<% @middles.each do |m| %>
    <%= link_to m.body, history_show_tweet_teacher_path(m.id, :student_id => @student.id) %>
<% end %>

<%= link_to "履歴削除", physical_destroy_tweet_teachers_path( :middle_id => @middle.id, :student_id => @student.id ), method: :patch %>

<div class="container">
    <div class="row">
        <% i=1 %>
        <% while i < 6 %>
            <div class="col-xs-6 col-sm-4">
                <div class="box">
                    <div class="subject">
                        <% s = @subjects.where(num:i).last %>
                        <% if s.present? %>
                            <%= s.body %>
                        <% end %>
                    </div>
                    <div class="tweets">
                        <% tweet_students = @tweet_students.with_deleted.where(num:i).order(id: :DESC) %>
                        <% tweet_students.each do |t| %>
                            <div class = "tweet">
                                <div class="field">
                                    <%= t.body %>
                                </div>
                                <div class="field">
                                    <%= t.notget %>
                                </div>
                                <div class="field">
                                    <%=  image_tag t.image_url, class: 'image' if t.image? %>
                                </div>
                                <div class="field">
                                    <%= t.achivement %>
                                </div>
                                <div class="field">
                                    <%= l t.created_at, format: :short %>
                                </div>
                                <div class="field">
                                    <i class="fas fa-heart"></i><%= t.likes.count %>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
                <% i=i+1 %>
            </div>
        <% end %>
    </div>
</div>

app/views/tweet_teachers/index.html.erb
<%= stylesheet_link_tag "calender", :media => "all" %>

<h2><%= @teacher.name %>先生の予定表</h2>

<div class="calender-container">
<%= link_to 'スケジュールを書く', new_schedule_path(:teacher_id => current_teacher.id) %>

<%= month_calendar events: @schedules do |date, schedule| %>
  <%= date.day %>
  <% schedule.each do |s| %>
    <div>
      <%= Student.find(s.student_id).name %>
      <%= link_to s.content, schedule_path(s.id) %>
    </div>
  <% end %>
<% end %>

</div>

app/views/tweet_teachers/show.html.erb
<h2><%= @teacher.name %>先生</h2>
<h3><%= @student.name %>の進捗</h3>

<div class="goal">
  <% if Conversation.where(teacher_id: current_teacher.id).where(student_id: @student.id).exists? %>
    <br>
    <%= link_to "チャットへ", conversation_path(current_teacher.conversations.find_by(student_id: @student.id)) %><br>
  <% else %>
    <%= form_for Conversation.new do |f| %>
      <%= f.hidden_field :student_id, :value => @student.id %>
      <%= f.submit %>
    <% end %>
  <% end %>
  <%= link_to "最終目標を設定する", new_final_path( :student_id => @student.id) %>
  <div class="final-container">
      <div class="final">
        <% if @final.present? %>
          <%= @final.body %>
        <% end %>
      </div>
  </div>
  <%= link_to "中間目標を設定する", new_middle_path( :student_id => @student.id) %>
  <div class="middle-container">
      <div class="middle">
        <% if @middle.present? %>
          <%= @middle.body %>
        <% end %>
      </div>
  </div>
</div>

<%= button_to "全部削除", all_destroy_tweet_teachers_path(@student.id), method: :patch %>
<%= link_to "履歴", history_index_tweet_teachers_path(@student.id) %>


<div class="container">
  <div class="row">
    <% i=1 %>
    <% while i < 6 %>
      <div class="col-xs-6 col-sm-4">
        <div class="box">
          <div class="subject bg-light text-dark">
            <%= link_to "科目を設定する", new_subject_path( :student_id => @student.id, :num => i) %>
            <% s = @subjects.where(num:i).last %>
            <% if s.present? %>
              <%= s.body %>
            <% end %>
          </div>
          <div class="todo">
            <%= link_to "Todoを設定する", new_todo_path( :student_id => @student.id, :num => i) %>
            <% t = @todos.where(num:i).last %>
              <% if t.present? %>
                <%= t.body %>
              <% end %>
          </div>
          <div class="tweets">
            <% tweet_students_data = @tweet_students.where(num:i).order(id: :DESC) %>
            <div class="overflow-auto" style="width:300px; height:400px;">
              <div class="tweet">
                <% tweet_students_data.each do |t| %>
                  <div class="field">
                    <%= t.body %>
                  </div>
                  <div class="field">
                      <%= t.notget %>
                  </div>
                  <div class="field">
                      <%=  image_tag t.image_url, class: 'image' if t.image? %>
                  </div>
                  <div class="field">
                      <%= t.achivement %>
                  </div>
                  <div class="field">
                    <%= l t.created_at, format: :short %>
                  </div>
                  <div class="field">
                    <% if current_teacher.already_liked?(t) %>
                      <%= link_to tweet_student_like_path(id: t.id, tweet_student_id: t.id), method: :delete do %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                      <% end %>
                    <% else %>
                        <%= link_to tweet_student_likes_path(id: t.id, tweet_student_id: t.id), method: :post do %>
                          <i class="fas fa-heart"></i><%= t.likes.count %>
                        <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="graph">
            <% subject = @subjects.where(num:i) %>
            <% subject.each do |s| %>
              <%= line_chart [ {name: s.body, data: @tweet_students.where(num:i).map{|t| t.slice(:created_at, :achivement).values} }] %>
            <% end %>
          </div>
        </div>
      <% i=i+1 %>
      </div>
    <% end %>
  </div>
</div>